import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "react-international-phone/style.css";
import "quill/dist/quill.snow.css";
import { ClerkProvider } from "@clerk/nextjs";
import PublicShell from "./components/PublicShell";
import { Toaster } from "sonner";
import RouteProgress from "./components/RouteProgress";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Eben Safaris",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased `}
        >
          <RouteProgress />
          <Toaster richColors position="top-right" />
          <PublicShell>{children}</PublicShell>
        </body>
      </html>
    </ClerkProvider>
  );
}
